CREATE TABLE dba_monitor_storage_snapshot (
    snapshot_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    captured_at TIMESTAMP WITH TIME ZONE
        DEFAULT SYSTIMESTAMP NOT NULL,
    tablespace_name VARCHAR2(128) NOT NULL,
    total_bytes NUMBER NOT NULL,
    used_bytes NUMBER NOT NULL,
    free_bytes NUMBER NOT NULL,
    CONSTRAINT pk_dba_monitor_storage_snapshot
        PRIMARY KEY (snapshot_id)
);

CREATE INDEX idx_dba_monitor_storage_snap_ts
ON dba_monitor_storage_snapshot (
    tablespace_name,
    captured_at
);