GRANT SELECT ON SYS.DBA_DATA_FILES TO FRANCISCO;

GRANT SELECT ON SYS.DBA_FREE_SPACE TO FRANCISCO;

GRANT SELECT ON SYS.DBA_SEGMENTS TO FRANCISCO;

GRANT CREATE TABLE TO FRANCISCO;

ALTER USER FRANCISCO QUOTA 50M ON USERS;